name: ChangeLog Generation

on:
  push:
    branches: [ develop, master ]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Standart-version
        run: sudo npm i -g standard-version

      - name: Check if changelog exist
        id: ch_check
        uses: andstor/file-existence-action@v1
        with:
          files: "CHANGELOG.md"

      - name: Bump Version
        if: steps.ch_check.outputs.files_exists == 'true'
        run: standard-version
      
      - name: Init Version
        if: steps.ch_check.outputs.files_exists == 'false'
        run: standard-version --first-release
    
      - name: Git Push Action
        uses: x-actions/git-push@v1
        with:
          GITHUB_EMAIL: ${{ github.actor }}@localhost
          GITHUB_USERNAME: ${{ github.actor }}
          PUBLISH_BRANCH: ${{ github.base_ref }}
