name: ChangeLog Generation

on: 
  pull_request:
    types: closed
    branches: 
      - master
      - develop

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install Standart-version
        run: sudo npm i -g standard-version

      - name: Check if changelog exist
        id: ch_check
        uses: andstor/file-existence-action@v1
        with:
          files: "CHANGELOG.md"
          
      - name: Setup Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Bump Version
        if: steps.ch_check.outputs.files_exists == 'true'
        run: standard-version
      
      - name: Init Version
        if: steps.ch_check.outputs.files_exists == 'false'
        run: standard-version --first-release
    
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop # ${{ github.base_ref }}
          tags: true
        
